### ISSUE TITLE
회원 / 김진아

### ISSUE THREAD

**Issue by jinainkorea** [ToTee-Block/Main#20]
---
|NAME|ABOUT|TITLE|LABELS|ASSINGEES|
|------|------|------|------|------|
|기본 이슈 템플릿|Todo 기록|회원 / 김진아|documentation|김진아|
---

## 작업 내역
- 회원가입
- 로그인
- 로그아웃
- 회원정보
- 매칭 신청
- 매칭 끊기
- 멘토 후기 작성

## TODO 
- [x] 회원가입 / 사용자 계정 생성
- 로그인
  - [x]  jwt 토큰 사용 
  - [x] 시큐리티 사용
- [x] 로그아웃 / 쿠키 삭제
- [x] 회원 정보 / 이메일 제외하고 사용자 정보 수정
- [x] 예외 처리 / 로그아웃된 상태, 사용자가 존재하지 않을 때, 권한이 없을 때
- 매칭 신청
  - [x] 일반 유저가 멘토에게 매칭 신청
  - [x] 매칭 신청된 목록을 멘토가 열람
- [x] 매칭 끊기 / 
- [ ] 멘토 후기 작성 / 

## 참고 사항
- 회원 정보에서 프로필 이미지 부분은 프론트 연결시 빈 파일 객체 삭제하고 파라미터값으로 수정하기
