### ISSUE TITLE
채팅 / 채팅창 프론트 / 이상수

### ISSUE THREAD

**Issue by LeeSamgsoo** [ToTee-Block/Main#22]
## 작업 내역
- 채팅 창 프론트 제작

## TODO
- [x] 주소/chatting 으로 들어가면 우측 하단에 채팅 창 버튼 뜨게 하기
- [x] 코드펜에 만들어둔 것들 next.js 형식에 맞게 바꾸기
- [x] 임시 채팅 창을 피그마와 최대한 똑같게 만들기
  - [x] 헤더 방 이름 중앙, 점 3개 오른쪽 위치 바꾸기
  - [x] 채팅 리스트 글자 줄이기
  - [x] 채팅 방 왼쪽에 불 뜨는 거 오른쪽으로 옮기기
  - [x] 채팅 입력 칸 왼쪽에 웃는 얼굴 아이콘 추가
  - [x] 채팅 입력 칸 오른쪽에 골뱅이 추가하고 전송 버튼 화살표로 바꾸기
  - [x] 채팅 화면에 날짜 뜨게하고, 채팅 하나마다 시간 뜨게 하기
  - [x] 상대가 채팅하면 이름과 프로필 뜨게 하기
- [x] 채팅 관련 엔티티 수정하기
- [x] 어쩌다 보니 백엔드랑 연동까지 함;
- [x] 채팅 과거 기록 가져오기
- [x] 채팅 치면 상대방도 똑같은 내용 쓰는 현상 고치기
- [x] 코드 수정 중에 헤더에 불필요한 내용 추가됨. 제거하고 수정

## 참고 사항
- 주소/chatting 은 실험용. 나중에 모든 페이지에 채팅 버튼 달면 지우기
- 현재 채팅창 열면 페이지의 헤더, 푸터 밀어내는 현상 있음
