### ISSUE TITLE
[이슈] 채팅 / 미비사항/ 이상수

### ISSUE THREAD

**Issue by LeeSamgsoo** [ToTee-Block/Main#51]
## 작업 내역
- 채팅 현재 미비사항 구현하기

## TODO
- 백 엔드
- [ ] 채팅 방 등록(머지한 뒤 만들 예정. 멘토 등록하면 그 멘토 전용 단체 방 자동 생성. 멘티 등록하면 멘토와 멘티 전용 1:1방 자동 생성)
- [ ] 읽음 표시 구현하기
- 프론트 엔드
- [x] 채팅 방 입장하면 최신 메세지가 보여지게 하기(스크롤 하단부터 보이게 하기)
- [x] 채팅 방이 켜지면 페이지의 헤더, 푸터 밀어내는 현상 해결하기
- [x] 채팅 방 드래그로 이동 가능
- [x] 레이아웃에 추가해서 모든 페이지에 채팅 버튼 추가
- [x] 전체 화면 사이즈가 커지면 드래그로 채팅 창 이동이 정상적으로 안 됨
- [ ] 삭제 버튼 추가
- [ ] 위젯 버튼 스타일 바꾸기
- [ ] 코드를 최대한 프로젝트 형식에 맞게 바꾸기
